### ISSUE TITLE
discussion mockCohortConstructor()

### ISSUE THREAD

**Issue by ilovemane** [OHDSI/CohortConstructor#103]
Do we want a mockCohortConstructor function built using omock, or just use omock inside test directly like they are now?

**Comment by edward-burn** [comment]
Let's dicuss this @ilovemane @nmercadeb @catalamarti

**Comment by catalamarti** [comment]
I think this functionality it is nice if they can do something like:
```
cdm <- mockCohortConstructor(numberIndividuals = 100)
```
and then they can test the different functions of the package
