### ISSUE TITLE
subsetCohorts - is it needed?

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/CohortConstructor#129]
@nmercadeb @catalamarti Not 100% sure, but can the same functionality not also be achieved via requireCohortIntersectFlag?

**Comment by nmercadeb** [comment]
I think it is not possible at the moment since only one target cohort id is allowed in requireCohortIntersectFlag

**Comment by catalamarti** [comment]
for me subsetCohorts is a nice functionality :)

**Comment by edward-burn** [comment]
ah I see I misunderstood what the function was for. Maybe a name like filterCohorts would be clearer?

**Comment by catalamarti** [comment]
subsetCohorts is fine for me
