### ISSUE TITLE
change name of the function unionCohorts

### ISSUE THREAD

**Issue by nmercadeb** [OHDSI/CohortConstructor#138]
Some ideas:
- combineCohorts
- mergeCohorts
- unioniseCohorts
- unifyCohorts

@edward-burn @catalamarti

**Comment by nmercadeb** [comment]
Also, should the `erafy()` function be changed to `erafyCohorts()` to be consisten with the other names?
![image](https://github.com/OHDSI/CohortConstructor/assets/61558739/294f0f4f-aa77-4918-becd-b9afdb39778f)

**Comment by catalamarti** [comment]
in principle erafy works for tables that are not cohorts
