### ISSUE TITLE
order by warning in intersect cohorts

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/CohortConstructor#158]
From the tests I see this warning:
  ── Warning ('test-intersectCohorts.R:30:3'): joinOverlap ───────────────────────
  ORDER BY is ignored in subqueries without LIMIT
  i Do you need to move arrange() later in the pipeline or use window_order() instead?

**Comment by nmercadeb** [comment]
I think we use arrange because omopgenerics method makes sure we keep the class?
https://github.com/darwin-eu-dev/omopgenerics/blob/8f96285a9d92fa7054791fbf53d1ab20e4c00d59/R/arrange.R#L19

@catalamarti
