### ISSUE TITLE
reexport checkCohorts 

### ISSUE THREAD

**Issue by nmercadeb** [OHDSI/CohortConstructor#160]
When omopgenerics new release

**Comment by nmercadeb** [comment]
This function is now deprecated in `omopgenerics` hahah should we reexport the validateCohortArgument function? Altough it might be confusing to have a validate argument function
https://darwin-eu-dev.github.io/omopgenerics/reference/checkCohortRequirements.html

**Comment by edward-burn** [comment]
yeah seems weird to reexport validateCohortArgument so let's close this (if we see we need something like this in the future CohortConstructor could have it's own function like checkCohorts)
