### ISSUE TITLE
source argument in conceptCohort?

### ISSUE THREAD

**Issue by catalamarti** [OHDSI/CohortConstructor#193]
Should we add an argument source (by default source = FALSE) that allow the user to use the source_concept_id column?

Related to #191

@nmercadeb @edward-burn 

If we do it for me the main question is if we restrict the concepts used in concept_id to standard and source_concept_id to non standard or we use all concepts for both columns

**Comment by edward-burn** [comment]
relates to #191, let's discuss!

**Comment by catalamarti** [comment]
hi we would need this for an study where we need to create cohorts based on source concepts.
Do you think this will be available soon? @nmercadeb @edward-burn

**Comment by catalamarti** [comment]
My proposal would be:
```
cohort <- conceptCohort(cdm = cdm, 
                        conceptSet = list(a = 1), 
                        name = "cohort",
                        source = TRUE) # by default we can set it to FALSE, but if true the column source_concept_id is also used
```
