### ISSUE TITLE
SubsetCohort - include a minimum count option

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/CohortConstructor#198]
Eg so that I can keep only the cohorts with at least 100 people etc

**Comment by edward-burn** [comment]
what do you think @nmercadeb @catalamarti? Seems like it would be useful functionality, but not sure if it would go in SubsetCohort or elsewhere?

**Comment by nmercadeb** [comment]
I like it! For me it fits with this function, so it subsets those ids fulfilling the cohort counts
