### ISSUE TITLE
Feature Request - a cohort_name argument in UnionCohorts

### ISSUE THREAD

**Issue by xihang-chen** [OHDSI/CohortConstructor#225]
So currently when we use UnionCohorts function, and run settings on the newly generated cohort, the cohort_name is the concatenation of the names of cohorts being unioned. It would be a good idea to have an argument that is down to user's choice.

**Comment by edward-burn** [comment]
Indeed. Something like cohortNameStyle would be nice for any function that takes one cohort and can make many in return, right @catalamarti @nmercadeb ?
