### ISSUE TITLE
Error in intersectCohorts - can't compute number_records

### ISSUE THREAD

**Issue by martapineda** [OHDSI/CohortConstructor#232]
Hi! We tried to intersect two drugs to obtain a cohort with the combination of both simultaneously, but is returning the following error:

![image](https://github.com/OHDSI/CohortConstructor/assets/90781436/26956495-951d-48bf-b381-346015cc49ed)

**Comment by edward-burn** [comment]
@martapineda @MimiYuchenGuo thanks for reporting. This should now be fixed on the main branch, can you please check?

**Comment by martapineda** [comment]
Confirm it is fixed! Thank you @edward-burn !!!
