### ISSUE TITLE
use omopgenerics check and validate functions

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/CohortConstructor#272]

**Comment by nmercadeb** [comment]
We are still using our own validate function for cohorts, but will update when issue #526 in omopgenerics is implemented. We can leave this issue as a remined or open a new one for this?
https://github.com/darwin-eu-dev/omopgenerics/issues/526

**Comment by nmercadeb** [comment]
Also to add omopgenerics' validateCohortId (https://github.com/darwin-eu-dev/omopgenerics/pull/530)

**Comment by nmercadeb** [comment]
To complete when:
https://github.com/darwin-eu-dev/omopgenerics/issues/624
https://github.com/darwin-eu-dev/omopgenerics/issues/623
