### ISSUE TITLE
rethink mutuallyExclusive argument in intesect

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/CohortConstructor#275]
Doesn´t seem particularly intuitive. Probaly we should either move/ remove it, or at least better explain it.

**Comment by nmercadeb** [comment]
Another issue in this function as is now, is that if `mutuallyExclusive` is TRUE, the argument ` keepOriginalCohorts` can be missleading since even though individual cohorts will be returned they might not be as the original (intersecctions will have been excluded)

**Comment by edward-burn** [comment]
As discussed:
1) Add "minus" cohorts as new cohorts rather than overwriting the old
2) rename "mutuallyExlusive" to "returnNonOverlappingCohorts"

**Comment by nmercadeb** [comment]
`returnNonOverlappingCohorts` defaulted to TRUE or FALSE? @edward-burn
