### ISSUE TITLE
measurementCohort - message about not used concepts 

### ISSUE THREAD

**Issue by nmercadeb** [OHDSI/CohortConstructor#287]
Maybe "these unit concepts don't exist ..." shouldn't be the meassage to indicate that these were not used in the measurement table for the concepts of interest?

What do you think about rephrasing to something like "these unit concepts were not used ..." ?

![image](https://github.com/user-attachments/assets/8f3befab-fab0-4875-a44c-26e2394e260e)

**Comment by edward-burn** [comment]
let's remove the message
