### ISSUE TITLE
add `subsetCohort` snf `subsetCohortId` arguments in `conceptCohort`

### ISSUE THREAD

**Issue by nmercadeb** [OHDSI/CohortConstructor#349]

**Comment by nmercadeb** [comment]
the subsetCohort will be used to subset to contributing individuals or also the time range (e.g. only create new cohort with events that happens when in the subsetCohort)?
In CDMConnector is the first, but in that case would it be worth to have only one argument refering to subjects?
@edward-burn

**Comment by edward-burn** [comment]
Just individuals and otherwise can use intersect/ union in the pipeline

I guess if you have multiple cohorts in the subsetCohort you might want to subset to just one (and then you would need to specify the ID as well as the table name)
