### ISSUE TITLE
padCohortEnd - option to ignore subsequent records in interval

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/CohortConstructor#363]
At the moment if a person has one cohort entry at day 0 and another entry at day 5, padCohortEnd with days=10 will lead to one entry starting on day zero and ending on day 15. It would be nice if their was an argument that allowed the second entry to be ignore the second event if in the window with the cohort then finishing at day 10

**Comment by catalamarti** [comment]
collapse = TRUE/FALSE,
if collapse = FALSE it will drop the overlapping records, would that work for you @edward-burn ?

**Comment by edward-burn** [comment]
yep!
