### ISSUE TITLE
Collapse overlapping cohorts

### ISSUE THREAD

**Issue by martaalcalde** [OHDSI/CohortConstructor#384]
https://ohdsi.github.io/CohortConstructor/reference/conceptCohort.html

Hi! I have a question regarding the "collapse of overlapping cohorts" that is conducted by default when creating a cohort using `conceptCohort()`. I think I don't quite understand how this is handled in different situations (i.e., different cohort_start_date,  different cohort_end_date). Does it only collapse those records that have identical "cohort_start_date" and "cohort_end_date"?

**Comment by nmercadeb** [comment]
it takes all the overlapping records and collapses them into one, for instance.:

``` r
# records in data
dplyr::tibble(
  cohort_definition_id = 1,
  subject_id = 1,
  cohort_start_date = as.Date(c("2000-01-01", "2000-01-31", "2000-01-10", "2000-02-16")),
  cohort_end_date = as.Date(c("2000-01-31", "2000-02-15", "2000-01-15", "2000-02-16"))
)
#> # A tibble: 4 × 3
#>      id start      end       
#>   <dbl> <date>     <date>    
#> 1     1 2000-01-01 2000-01-31
#> 2     1 2000-01-31 2000-02-15
#> 3     1 2000-01-10 2000-01-15
#> 4     1 2000-02-16 2000-02-16


# after collapsing
dplyr::tibble(
  cohort_definition_id = 1,
  subject_id = 1,
  cohort_start_date = as.Date(c("2000-01-01", "2000-02-16")),
  cohort_end_date = as.Date(c("2000-02-15", "2000-02-16"))
)
#> # A tibble: 2 × 3
#>      id start      end       
#>   <dbl> <date>     <date>    
#> 1     1 2000-01-01 2000-02-15
#> 2     1 2000-02-16 2000-02-16
```

<sup>Created on 2024-12-17 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
