### ISSUE TITLE
matchCohort - names of new cohort

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/CohortConstructor#390]
Let's say we have an asthma cohort of 1000 people (that we called **_asthma_**). When we do matching we get two new cohorts:
- cohort_1: 900 people from the asthma cohort who we could find a match in the general database population, and 
- cohort_2: 900 people from the general population who we matched to cohort_1

The naming convention for the two new cohorts would be:
- cohort_1: **_asthma_matched_** 
- cohort_2: **_matched_to_asthma_**

However, already for one study we changed this in the shiny app to:
- cohort_1: **_asthma_sample_** 
- cohort_2: **_asthma_matched_**

Need to decide what the naming convention is

**Comment by daniprietoalhambra** [comment]
I would certainly prefer the latter:
- cohort_1: **_xxxx_sample_**
- cohort_2: **_xxxx_matched_**

**Comment by daniellenewby** [comment]
cohort_1: asthma_sample
cohort_2: asthma_matched

Would make it consistent with phenotypeR
