### ISSUE TITLE
Add parameter to add records (instead of concatenating them) when collapsing cohorts

### ISSUE THREAD

**Issue by martaalcalde** [OHDSI/CohortConstructor#391]
Currently, `conceptCohort()` function concatenates overlapping cohorts:

i.e.: 1st record: Jan. 1st to Jan 10th
       2nd record: Jan. 7th to Jan 15th.
       Collapsed cohort: Jan. 1st to Jan 15th

Add parameter so that the records are added:
i.e.: 1st record: Jan. 1st to Jan 10th
       2nd record: Jan. 7th to Jan 15th. 
       Collapsed cohort (3 overlapping days are added to the end of the cohort end date):: Jan. 1st to Jan 18th

**Comment by edward-burn** [comment]
Maybe we can have one argument (overlap) that has three options:
- concatanate (current behaviour) - end date would be 15th
- drop (ignores the second record) - end date would be 10th
- add (adds the second record to the first) - end date would be 18th
