### ISSUE TITLE
measurementCohort

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/CohortConstructor#82]
conceptCohort + requirement around test result (value_as_number, value_as_concept_id) and unit_concept_id

**Comment by nmercadeb** [comment]
Should we somehow add the information of `valueAsConcept` and `valueAsNumber` in the attribute `cohort_codelist`?

**Comment by edward-burn** [comment]
@nmercadeb I wouldn't worry about that now, but let's leave this open to tackle later
