### ISSUE TITLE
revise defaults

### ISSUE THREAD

**Issue by nmercadeb** [OHDSI/CohortConstructor#85]
- window 
- dateRange
- arguments in require demographics and dervied functions

**Comment by edward-burn** [comment]
remove default from requireSex etc https://github.com/OHDSI/CohortConstructor/blob/0046c78238690c041d3756125785464ccbbe9cfb/R/requireDemographics.R#L124C30-L124C39

But leave defaults for requireDemographics (as user may be only interested in one or two)

**Comment by edward-burn** [comment]
no window default and move to top
